package com.rsshool2021.android.pomodoro

const val ADD_TIMER_FRAGMENT_TAG = "ADD_TIMER_FRAGMENT"
const val ADD_TIMER_REQUEST_KEY = "ADD_TIMER_REQUEST_KEY"
const val TIMER_BUNDLE_PERIOD_KEY = "TIMER_BUNDLE_PERIOD_KEY"